---
title: "About"
subtitle: "More about who I am—what I do and what I love"
title-block-banner: true
---

## Profession 

I’m a data science and machine learning professional passionate about solving meaningful challenges at the intersection of data, business, and technology. My journey began at BITS Pilani, but it was during my time at JioCinema that I developed a strong interest in building end-to-end data systems — from training models and extracting insights to optimizing data pipelines. I’m drawn to roles where data science isn’t just an auxiliary function, but a core driver of product innovation and business growth.

### Experience

- **Data Science and Anaytics at JioCinema, Viacom18** | Aug 2023 – Nov 2024 <br>
   At JioCinema, I worked across the full spectrum of data science — from machine learning and analytics to data engineering. I built ML models to infer user attributes and preferences, directly supporting ad targeting and content strategy. Alongside this, I developed internal ML-powered tools and worked closely on reporting systems that supported both product and business decisions. My role extended into data engineering, where I designed and optimized data pipelines, designed data quality monitoring frameworks, and worked with large-scale datasets to improve processing efficiency. I was also closely involved in the JioCinema–Hotstar merger, where I contributed to data migration and user transition efforts — ensuring continuity across systems, content, and user experience. This holistic exposure gave me a deep understanding of what it takes to translate raw data into scalable, production-ready systems that deliver business impact.

- **Data Science and Anaytics at JioHotstar, Star India** | Nov 2024 – Present <br>
   After the merger of JioCinema and Hotstart into JioHotstar, I’ve focused on bringing data science closer to the user experience, especially around live sports and entertainment. My work here includes building predictive models that support real-time insights, analyzing user behavior to inform product design, and collaborating on A/B experiments to test and refine new features. I’ve been deeply involved in A/B testing — from experiment design to result interpretation — helping product teams make data-driven decisions at scale. This role has further strengthened my ability to apply both machine learning and analytics in fast-moving, user-facing environments.

##  Hobby 

I’m a huge fan of martial cultivation stories, especially mangas, manhwas, and web novels. There’s just something about the mix of intense action, character growth, and world-building that really pulls me in. I love watching a protagonist start out small, slowly mastering their skills, and then seeing them face epic battles as they grow stronger. It’s the kind of story that can keep me hooked for hours. Every universe feels so unique, and I enjoy following the characters as they push their limits and discover what they’re truly capable of.



